Repository kaustubhgupta/Hacktoberfest, pull requests merged in 2020-10, with the labels that each got.

#53 Pancake Sorting Algorithm
  PancakeSort.cpp
Labels: hacktoberfest

#84 Segment Tree Build ,Range Update,Point Update And Range Query
  C++/Segment Tree/segment_tree_build_update_query.cpp
Labels: c++, hacktoberfest, medium

#48 Added DP algorithms for Java Project
  Java/CoinChange.java
  Java/LongestIncreasingSubsequence.java
Labels: documentation, good first issue, hacktoberfest

#41 fixed #76 added RevDoublyLinkedList.c
  C++/RevDoublyLinkedList.c
Labels: c++, good first issue, medium

#92 Added my game
  Python/word-guess.py
Labels: good first issue, hacktoberfest, python

#47 added more info
  C/README.md
  HTML/README.md
  queue_using_stack.c
Labels: good first issue, hacktoberfest

#101 Added BST.cpp
  C++/BST.cpp
Labels: c++, hacktoberfest, intermediate

#106 Added Doubly Linked List in C
  C/doublyLinkedList.c
Labels: C

#123 Add API REST with Node and Express
  Others/API-REST-Node/.gitignore
  Others/API-REST-Node/APIClients.postman_collection.json
  Others/API-REST-Node/README.md
  Others/API-REST-Node/data.json
  Others/API-REST-Node/package.json
  Others/API-REST-Node/server.js
  Others/API-REST-Node/yarn.lock
Labels: hacktoberfest-accepted, javascript, medium

#93 palindromic sub sequence
  .gitignore
  Java/PalindromeSubSequence.java
Labels: hacktoberfest, java

#156 Binary Search Tree implementation in C
  C/BinarySearchTree.c
  C/README.md
Labels: C, hacktoberfest-accepted

#148 Added Calculator program and menu screenshot
  Java/Calculator/Calculator.java
  Java/Calculator/menu.png
  Java/README.md
Labels: java

#109 Copy content of one directory in other.
  Java/DirectoryHandlerJava.java
  Java/README.md
Labels: java, need improvement

#167 floyds cycle detection algorithm
  C/README.md
  C/floyds_cycle_detection_for_linked_lists.c
Labels: C, hacktoberfest-accepted

#226 [Issue - 107 ]Added Egg dropping Puzzle Solution in C
  C/EggDroppingPuzzle.c
  C/README.md
Labels: need improvement

#254 Added the code to extract the YouTube Trending Page Data
  Python/README.md
  Python/YouTube_Trending_Analysis/Trending_Page_Data.csv
  Python/YouTube_Trending_Analysis/YT_Trending_Analysis.py
Labels: documentation, need improvement

#282 #248 Anagrams programs
  Python/README.md
  Python/anagram.py
Labels: good first issue, hacktoberfest-accepted

#278 #225 LCS and Longest palindromic substring
  C++/README.md
  C++/longest_common_subsequence.cpp
  C++/longest_palindromic_subsequence.cpp
Labels: good first issue, hacktoberfest-accepted

#264 Adding Code of Game
  C/Guessing Game/GuessingGame.PNG
  C/Guessing Game/main.c
  C/README.md
Labels: need improvement

#269 added 3 java programs
  Java/README.md
  Java/factorial.java
  Java/fibonacci.java
  Java/swapTwoNumbers.java
Labels: need improvement

#290 LinearSearch_Python
  Python/README.md
  Python/binarysearch.py
  Python/linearsearch.py
Labels: documentation, need improvement

#292 A convertor from Prefix to Postfix and Infix expressions.
  C++/README.md
  C++/prefixConverter.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#293 Fast io
  Java/README.md
  Java/fastIO/Reader.java
  Java/fastIO/ReaderTest.java
  Java/fastIO/Writer.java
  Java/fastIO/WriterTest.java
Labels: hacktoberfest, need improvement

#304 [hacktoberfest] solution for game randow number [Java]
  Java/README.md
  Java/WhatIsNumberGame.java
Labels: documentation

#313 Quick sort added
  C++/Quick_Sort.cpp
  C++/README.md
Labels: documentation

#319 Add Subsets of a String to Java
  Java/README.md
  Java/SubsetsOfAString.java
Labels: need improvement

#323 Python string subset rec
  Python/README.md
  Python/stringSubsetsRecursive.py
Labels: documentation

#358 added: CarGame under Python
  Python/Car_Game/CarGame.py
  Python/Car_Game/car-game.png
  Python/README.md
Labels: need improvement

#288 Added code for MST
  C++/MST_Kruskals.cpp
  C++/MST_Prims.cpp
  C++/README.md
Labels: bug, need improvement

#326 Kadane's algorithm in python
  Python/README.md
  Python/kadanes_algorithm.py
Labels: need improvement

#341 Create PrefixConversion.java
  Java/PrefixConversion.java
  Java/README.md
Labels: question

#333 adding kadane's algorithm in c
  C/README.md
  C/kadane.c
Labels: question

#330 Add recursivePowerSetOfString.cpp to C++
  C++/README.md
  C++/recursivePowerSetOfString.cpp
Labels: question

#364 Added Minimum Spanning Tree Algorithms for Java Project
  Java/Graphs/KruskalsAlgorithm.java
  Java/Graphs/PrimsAlgorithm.java
  Java/README.md
Labels: help wanted

#357 Added Extra Long Factorial
  Java/ExtraLongFactorial.java
  Java/README.md
Labels: help wanted

#379 Linked List Insertion in C++
  C++/README.md
  C++/singlyLinkedList.cpp
Labels: need improvement

#352 Added Dijkstra Algorithm
  C++/Dijkstras_Algorithm/dijkstras_algorithm_sssp.cpp
  C++/README.md
Labels: Second Review

#345 Added Bucket, Shell and Radix Sort
  Java/BucketSort.java
  Java/README.md
  Java/RadixSort.java
  Java/ShellSort.java
Labels: bug, need improvement

#376 Create reverse_doubly_linked_list.java
  Java/README.md
  Java/reverseDoublyLinkedList.java
Labels: documentation

#410 init notify_me project
  Python/README.md
  Python/notify_me/README.md
  Python/notify_me/notification_icon.ico
  Python/notify_me/notify-me.bat
  Python/notify_me/notify-me.py
Labels: documentation

#437 Added Quick Sort
  Java/QuickSort.java
  Java/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#443 Add files via upload
  Java/README.md
  Java/Trie_Implementation.java
Labels: documentation

#455 Added Breadth First Search
  C/BFS_AdjacencyList.c
  C/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#493 Add discord messager bot
  Python/README.md
  Python/discord_messager_bot/discord.mp4
  Python/discord_messager_bot/discordMessagesBot.py
Labels: need improvement

#530 Added Counting Sort algorithm in C++
  C++/README.md
  C++/countingSort.cpp
Labels: need improvement

#541 Added postfix evaluation C++ code
  C++/Postfix_Evaluation.cpp
  C++/README.md
Labels: documentation

#550 Added Counting Sort in Python
  Python/CountingSort.py
  Python/README.md
Labels: need improvement
