Repository kaustubhgupta/Hacktoberfest, pull requests merged in 2021-10, with the labels that each got.

#613 Updated " C++/fah_to_cel_function(CB).cpp "
  C++/fah_to_cel_function(CB).cpp
Labels: need improvement, Under Review

#614 Added a feature in Python/Fahrenheit_to_celsius.py
  Python/Fahrenheit_to_celsius.py
Labels: hacktoberfest-accepted, 2021

#625 Added : Code for Key Pad Problem in Java
  Java/KeyPadProblem.java
Labels: hacktoberfest-accepted, 2021

#642 Kahn's Algorithm
  Java/Graphs/KahnsAlgorithm.java
Labels: hacktoberfest-accepted, 2021

#653 Added TwoSum.cpp for issue #634
  C++/TwoSum.cpp
Labels: hacktoberfest-accepted, 2021

#662 AB - adding Philosopher dining problem
  Java/DiningPhilosophersProblem/.classpath
  Java/DiningPhilosophersProblem/.project
  Java/DiningPhilosophersProblem/.settings/org.eclipse.jdt.core.prefs
  Java/DiningPhilosophersProblem/bin/it/philosophers/Main.class
  Java/DiningPhilosophersProblem/bin/it/philosophers/exceptions/onlyOnePhilosopherException.class
  Java/DiningPhilosophersProblem/bin/it/philosophers/manager/TableManager.class
  Java/DiningPhilosophersProblem/bin/it/philosophers/model/Fork.class
  Java/DiningPhilosophersProblem/bin/it/philosophers/model/Philosopher.class
  Java/DiningPhilosophersProblem/bin/it/philosophers/model/Status.class
  Java/DiningPhilosophersProblem/src/it/philosophers/Main.java
  Java/DiningPhilosophersProblem/src/it/philosophers/exceptions/onlyOnePhilosopherException.java
  Java/DiningPhilosophersProblem/src/it/philosophers/manager/TableManager.java
  Java/DiningPhilosophersProblem/src/it/philosophers/model/Fork.java
  Java/DiningPhilosophersProblem/src/it/philosophers/model/Philosopher.java
  Java/DiningPhilosophersProblem/src/it/philosophers/model/Status.java
Labels: hacktoberfest-accepted, 2021

#617 Added Code for Shell Sort, closes #637
  C++/ShellSort.cpp
Labels: hacktoberfest-accepted, 2021

#612 Number Guess Game.py
  Python/Number Guess Game.py
Labels: hacktoberfest-accepted, 2021

#667 Grid Travel Problem Java Solution
  Java/DynamicProgramming/GridTravel.java
Labels: hacktoberfest-accepted, 2021

#668 Binary Exponentiation Added
  Java/Others/BinaryExponentiation.java
Labels: hacktoberfest-accepted, 2021

#669 Added : Code for Tower of Hanoi Problem in Java
  Java/Others/TowerOfHanoi.java
Labels: hacktoberfest, 2021

#670 Added UnionFind.java
  Java/DisjointSetUnion/UnionFind.java
Labels: hacktoberfest, 2021

#673 K largest elements in array using heap
  Java/heap/KLargestElementsInArrayUsingHeap.java
Labels: hacktoberfest, 2021
